### ISSUE TITLE
"super" admin

### ISSUE THREAD

**Issue by neiljohari** [neiljohari/scram#6]
it is worth considering a "super" admin kind of permission, but we may be better off leaving this up to the implementer somehow.

one possible solution to implement it in scram: allow string permissions with empty conditions to permit the actions on any object.

to let implementer decide: they can reopen the Target class, alias the old `can?` method, and make their own that can check a boolean or something prior to calling the original `can?` method

**Comment by Spaceghost** [comment]
```
def can?
  super unless bypass_permissions
end
```

bypass_permissions
